// Generated by Wrangler by running `wrangler types`

interface Env {
	SERVICE_NAME: "cloudflare-agentic-ai-browser";
	logpush: true;
	tail_consumers: [{"service":"cloudflare-agentic-ai-browser-tail","environment":"undefined"}];
	BROWSER: DurableObjectNamespace /* Browser */;
	BUCKET: R2Bucket;
	DB: D1Database;
	RATE_LIMITER: RateLimit;
	OPENAI_API_KEY: string;
	GEMINI_API_KEY: string;
	ACCOUNT_ID: string;
	MYBROWSER: any;
}
