// Generated by Wrangler by running `wrangler types`

interface Env {
	SERVICE_NAME: "cloudflare-agentic-ai-browser";
	logpush: true;
	tail_consumers: [{"service":"cloudflare-agentic-ai-browser-tail","environment":"undefined"}];
	BROWSER: DurableObjectNamespace<import("./src/index").Browser>;
	BUCKET: R2Bucket;
	DB: D1Database;
	RATE_LIMITER: RateLimit;
}
