name: Update pnpm lockfile

"on":
  push:
    paths:
      - 'package.json'
    branches:
      - main
      - master

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    
    # Skip if the commit message contains '[skip-lockfile]' to prevent infinite loops
    if: "!contains(github.event.head_commit.message, '[skip-lockfile]')"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Use a token that can push to protected branches if needed
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies and update lockfile
        run: pnpm install --no-frozen-lockfile
        
      - name: Commit and push updated lockfile
        uses: EndBug/add-and-commit@v9
        with:
          add: 'pnpm-lock.yaml'
          message: 'chore: update pnpm-lock.yaml [skip-lockfile]'
          default_author: github_actions
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}